name = "cf-worker-image-converter"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
CLOUDINARY_CLOUD_NAME = ""
CLOUDINARY_API_KEY = ""
CLOUDINARY_API_SECRET = ""

[build]
command = "npm run build"